### ISSUE TITLE
HU03 Consultar el listado de artistas

### ISSUE THREAD

**Issue by taganga** [MISW-DesarrolloMovil-202215/MISW-DesarrolloMovil-202215#3]
<html><body>

Identificador | HU03
-- | --
Nombre | Consultar el listado de artistas
Descripción | **Como** usuario visitante **quiero** ver el listado de artistas **para** escoger lo que más me interesa.
Criterios de aceptación | El campo de artista no puede ir vacío ni estar repetido con un artista ya registrado.
  | Se debe acceder al listado de artistas a través del botón de Artistas.
  | Se debe contar con un botón de cancelar que redireccione al página de ver perfil.
  | Se deberá mostrar cada nombre de artista en el listado.
  | Se debe realizar el desarrollo mediante TDD.
  | Se deberá mostrar al lado del nombre del artista una imagen que lo represente.
Mockup |  ![Image](https://user-images.githubusercontent.com/66291589/196008899-e12208c7-2227-47f4-a889-cccdf2055344.png)

</body>
</html>

**Comment by anfedelahoz** [comment]
Close #3
