### ISSUE TITLE
HU04 Consultar la información detallada de un artista

### ISSUE THREAD

**Issue by taganga** [MISW-DesarrolloMovil-202215/MISW-DesarrolloMovil-202215#4]
<html><body>

Identificador | HU04
-- | --
Nombre | Consultar la información detallada de un artista
Descripción | **Como** usuario visitante **quiero** ver el listado de artistas **para** escoger lo que más me interesa.
Criterios de aceptación |  En el detalle del artista se debe mostrar el nombre, la imagen asociada y una descripción del artista.
  | Se debe acceder al detalle del artista a partir del listado de los mismos.
  | Se debe realizar el desarrollo mediante TDD.
Mockup |  ![Image](https://user-images.githubusercontent.com/66291589/196008913-d42a5776-2a2a-47e9-b2a8-d6a2d19130e2.png)

</body>
</html>

**Comment by anfedelahoz** [comment]
Close #4
