### ISSUE TITLE
Isuee #3 Microoptimización: Invalidación de los datos de AllRecyclerView

### ISSUE THREAD

**Issue by anfedelahoz** [MISW-DesarrolloMovil-202215/MISW-DesarrolloMovil-202215#59]
**Detalle del Issue**
Se encuentra ineficiencia al implementar el método `notifyDataSetChanged`.

**Contexto de la prueba**
IDE Android Studio 

**Pasos reproducción del defecto**
1. En Android Studio, seleccione sobre la barra superior la opción de _Code_.
2. Seleccione _Inspect code_.
3. Se abrirá una ventana emergente con configuraciones por defecto. De clic en _Ok_ para ejecutar la inspección con la configuración seleccionada.

![image](https://user-images.githubusercontent.com/66291589/202871773-144c9c8a-3652-4963-9c66-95b74f7bb8d0.png)

**Comment by taganga** [comment]
![image](https://user-images.githubusercontent.com/98675608/202872503-64468dc2-26b4-4b00-b440-dce9f6364dd1.png)

Se realiza la micro optimización, reemplazando el método anterior por métodos que realizan notificaciones de eventos más específicos.
