### ISSUE TITLE
Isuee #4 Microoptimización: Obsolete layout params

### ISSUE THREAD

**Issue by taganga** [MISW-DesarrolloMovil-202215/MISW-DesarrolloMovil-202215#60]
**Detalle del Issue**
Se encuentra advertencia obsolescencia 'Obsolete layout params'.

**Contexto de la prueba**
IDE Android Studio 

**Pasos reproducción del defecto**
1. En Android Studio, seleccione sobre la barra superior la opción de _Code_.
2. Seleccione _Inspect code_.
3. Se abrirá una ventana emergente con configuraciones por defecto. De clic en _Ok_ para ejecutar la inspección con la configuración seleccionada.
![isuee4](https://user-images.githubusercontent.com/98675608/202872288-9a252900-d2b7-4a43-a81f-5529ddcd0168.PNG)

**Comment by taganga** [comment]
![image](https://user-images.githubusercontent.com/98675608/202872449-4fb4e26e-ee96-4e7a-8110-475eae097eb1.png)


Se realiza la micro optimización, reemplazando el método anterior por métodos que realizan notificaciones de eventos más específicos.

**Comment by anfedelahoz** [comment]
Se retira parámetro obsoleto en la definición de cada RelativeLayout y TextView, se ejecutaron pruebas Espresso para validar el correcto funcionamiento de la aplicación. 
![isuee4_1](https://user-images.githubusercontent.com/66291589/202873658-2394a8b2-dd6d-4e1b-a90a-4bb1f85bea64.PNG)
![isuee4_2](https://user-images.githubusercontent.com/66291589/202873659-9885a5d6-3e48-4104-b8b0-6ef86a0bf73e.PNG)
