### ISSUE TITLE
Isuee #9 Microoptimización: Implementacion de Corrutinas

### ISSUE THREAD

**Issue by taganga** [MISW-DesarrolloMovil-202215/MISW-DesarrolloMovil-202215#65]
**Detalle del Issue**
Refactorizar código implementado Corrutinas. Esto nos va a permitir bloquear la ejecución de la corrutina mientras ejecutan su trabajo, y tienen la particularidad de retornar el resultado de la operación para su posterior uso.

**Comment by jacostaj** [comment]
Se incluye la dependencia para utilizar corrutinas dentro de la aplicación.
![corr1](https://user-images.githubusercontent.com/99131616/202926356-c3c51c36-a657-47c5-b51c-f1c5063dfaec.JPG)
