### ISSUE TITLE
Isuee #10 Optimización: Implementacion de Cache

### ISSUE THREAD

**Issue by taganga** [MISW-DesarrolloMovil-202215/MISW-DesarrolloMovil-202215#66]
Implementar uso de cache para descargar imágenes y guardarlas en caché luego será utilizadas posteriormente por la aplicación

**Comment by jacostaj** [comment]
Librería presentada por Bumptech para descargar imágenes y guardarlas en caché para ser utilizadas posteriormente por la aplicación Android
![imagen](https://user-images.githubusercontent.com/99131616/202942830-a7b4748b-b66d-4b82-acc7-82040ab20fc9.png)

Se cre un archivo BindingUtils con la siguiente configuración donde **Glide** requiere que se invoque una función de forma programática para asignar una imagen a un elemento ImageView, se hace una invocación en el método onBindViewHolder del adaptador, en la clase AlbumsAdapter y se incluye el llamado del bind, el método onBindViewHolder.
Glide internamente averigua si la imagen está siendo utilizada en otra vista; luego, consulta el caché de memoria, a ver si la imagen se ha cargado recientemente.
**.diskCacheStrategy()**   y acepta valores para almacenar en el caché de disco la información de datos crudos y/o recursos decodificados, o ninguno
**.onlyRetrieveFromCache()** fuerza a Glide a utilizar imágenes únicamente si están en el caché.
**DiskCacheStrategy** fuerza a Glide a saltar las consultas de caché de disco o de memoria.
![imagen](https://user-images.githubusercontent.com/99131616/202942981-52a15b78-18b5-4e17-850d-4a4d24341d17.png)
