### ISSUE TITLE
Isuee #12 Microoptimización: Unused resources

### ISSUE THREAD

**Issue by taganga** [MISW-DesarrolloMovil-202215/MISW-DesarrolloMovil-202215#81]
Validar si recursos se encuentran en uso

![image](https://user-images.githubusercontent.com/98675608/205524748-82fbf2a4-186e-44bb-9292-38aee37b103c.png)

**Comment by anfedelahoz** [comment]
Se implementa la microoptimización eliminando los recursos no utilizados.

**Antes:**
![image (1)](https://user-images.githubusercontent.com/66291589/205526036-3f6af5e2-b518-45e5-bff1-775b3ac6131e.png)

**Después:**
![image](https://user-images.githubusercontent.com/66291589/205526037-6350130e-c650-428f-8b2b-f93102d96b56.png)
