### ISSUE TITLE
Isuee #13 Microoptimización: Unnecessary parent layout

### ISSUE THREAD

**Issue by taganga** [MISW-DesarrolloMovil-202215/MISW-DesarrolloMovil-202215#82]
Detalle del Issue
Se encuentra advertencia la maquetación de layouts, en la que se indica que contenedor padre es innecesaria 'Unnecessary parent layout'.

Contexto de la prueba
IDE Android Studio

Pasos reproducción del defecto

En Android Studio, seleccione sobre la barra superior la opción de Code.
Seleccione Inspect code.
Se abrirá una ventana emergente con configuraciones por defecto. De clic en Ok para ejecutar la inspección con la

![image](https://user-images.githubusercontent.com/98675608/205524886-25a8a8d4-c279-4fc4-92b8-82538cf5c75e.png)

**Comment by anfedelahoz** [comment]
Se realizan pruebas manuales de visualización de los layout reportados, se trata de reconfigurar la maquetación eliminando o fusionándolos las propiedades con le contenedor principal y se concluye que es necesario los contenedores padres. Se reporta como un falso positivo
